# Generated by Django 3.0.4 on 2020-06-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('month', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
                ('is_archived', models.BooleanField()),
                ('initial_amout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amout', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('amout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_archived', models.BooleanField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
    ]
