# Generated by Django 3.0.4 on 2020-06-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charges',
            new_name='Charge',
        ),
    ]
