# Generated by Django 3.0.4 on 2020-06-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200603_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='initial_amout',
            new_name='initial_amount',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='total_amout',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='amout',
            new_name='amount',
        ),
    ]
